apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudops-data
  namespace: cloudops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath
